// holds colors used for dwm
static const char col_white[]       = "#ffffff";
static const char col_black[]       = "#101010";
static const char col_gray1[]       = "#0f0f0f";
static const char col_gray2[]       = "#444444";
static const char col_gray3[]       = "#bbbbbb";
static const char col_gray4[]       = "#eeeeee";
static const char col_blue1[] 	    = "#1071b2";
static const char col_blue2[]	    = "#224488";
static const char col_green[]       = "#295340";
static const char col_purpl[]       = "#725ddd";
